// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CascaderArea: typeof import('./src/components/cascader/CascaderArea.vue')['default']
    CascaderDemo: typeof import('./src/components/cascader/CascaderDemo.vue')['default']
    DialogConfirm: typeof import('./src/components/dialog-confirm/DialogConfirm.vue')['default']
    DialogFilePreview: typeof import('./src/components/dialog-file-preview/DialogFilePreview.vue')['default']
    DialogHtml: typeof import('./src/components/dialog-html/DialogHtml.vue')['default']
    DialogImport: typeof import('./src/components/dialog-import/dialog-Import.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/SearchBar.vue')['default']
    SearchBarLeft: typeof import('./src/components/search-bar/SearchBarLeft.vue')['default']
    SearchBarRight: typeof import('./src/components/search-bar/SearchBarRight.vue')['default']
    SelectDemo: typeof import('./src/components/select/SelectDemo.vue')['default']
    SelectTreeDemo: typeof import('./src/components/select/SelectTreeDemo.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TableList: typeof import('./src/components/table-list/TableList.vue')['default']
    TableListC: typeof import('./src/components/table/TableListC.vue')['default']
    TableListEmpty: typeof import('./src/components/table-list/TableListEmpty.vue')['default']
    TableSearch: typeof import('./src/components/table/table-search/TableSearch.vue')['default']
    TableSearchSave: typeof import('./src/components/table/table-search/TableSearchSave.vue')['default']
    TableTree: typeof import('./src/components/table/TableTree.vue')['default']
    Tabs: typeof import('./src/components/tabs/Tabs.vue')['default']
    TabsItem: typeof import('./src/components/tabs/TabsItem.vue')['default']
    Tree: typeof import('./src/components/table/Tree.vue')['default']
    TreeDemo: typeof import('./src/components/tree/TreeDemo.vue')['default']
    UpLoadFile: typeof import('./src/components/UpLoadFile.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
